(function(){
  'use strict';
  const $=s=>document.querySelector(s), state={data:null,active:null,progress:read('study-progress',{}),collapsed:read('gulu-collapsed',{}),notes:[],last:localStorage.getItem('gulu-last-course')||'',notesOpen:localStorage.getItem('gulu-notes-open')!=='0'};
  const el={app:$('#app'),list:$('#courseList'),search:$('#search'),viewer:$('#viewer'),wrap:$('.viewer-wrap'),welcome:$('#welcome'),section:$('#sectionName'),course:$('#courseName'),progressText:$('#progressText'),progressPct:$('#progressPct'),progressFill:$('#progressFill'),notes:$('#notesPanel'),notesList:$('#notesList'),notesHint:$('#notesHint'),notesTitle:$('#notesTitle'),noteCount:$('#noteCount'),mark:$('#markDone'),open:$('#openPage'),toast:$('#toast')};
  function read(k,fallback){try{return JSON.parse(localStorage.getItem(k))||fallback}catch{return fallback}}
  function save(k,v){try{localStorage.setItem(k,JSON.stringify(v))}catch{toast('浏览器存储空间不足')}}
  function toast(msg){el.toast.textContent=msg;el.toast.classList.add('show');clearTimeout(toast.t);toast.t=setTimeout(()=>el.toast.classList.remove('show'),2400)}
  function esc(s){return String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
  function allCourses(){return state.data?state.data.sections.flatMap(s=>s.courses.map(c=>({...c,section:s}))):[]}
  function catalogGroups(){
    if(!state.data?.groups?.length)return[{id:'all',title:'全部课程',description:'',sections:state.data?.sections||[]}];
    const byId=new Map(state.data.sections.map(s=>[s.id,s]));
    return state.data.groups.map(g=>({...g,sections:g.sections.map(id=>byId.get(id)).filter(Boolean)}));
  }
  function render(filter=''){
    const q=filter.trim().toLowerCase();el.list.innerHTML='';
    catalogGroups().forEach(g=>{const group=document.createElement('div');group.className='catalog-group';let visible=0;group.innerHTML=`<div class="catalog-label"><b>${esc(g.title)}</b><span>${esc(g.description||'')}</span></div>`;
      g.sections.forEach(s=>{const courses=s.courses.filter(c=>!q||c.title.toLowerCase().includes(q)||c.tags.some(t=>t.toLowerCase().includes(q)));if(!courses.length)return;visible++;
        const box=document.createElement('section');box.className='section'+(state.collapsed[s.id]&&!q?' closed':'');box.innerHTML=`<div class="section-head"><span class="section-icon" style="color:${s.color};background:${s.color}1f">${esc(s.icon)}</span><span>${esc(s.title)}</span><i class="chev">▾</i></div><div class="section-courses"></div>`;
        box.querySelector('.section-head').onclick=()=>{state.collapsed[s.id]=!state.collapsed[s.id];save('gulu-collapsed',state.collapsed);box.classList.toggle('closed')};const list=box.querySelector('.section-courses');
        courses.forEach(c=>{const row=document.createElement('div');row.className='course'+(state.active?.id===c.id?' active':'')+(state.progress[c.id]?' done':'');row.dataset.id=c.id;row.innerHTML=`<span class="check">${state.progress[c.id]?'✓':''}</span><span class="course-title">${esc(c.title)}</span>`;row.onclick=()=>openCourse(c,s);row.querySelector('.check').onclick=e=>{e.stopPropagation();toggleProgress(c.id)};list.appendChild(row)});group.appendChild(box)
      });if(visible)el.list.appendChild(group)
    });
    if(!el.list.children.length)el.list.innerHTML='<p style="padding:25px;color:var(--mute);font-size:12px">没有找到匹配课程</p>';updateProgress()
  }
  function updateProgress(){const all=allCourses(),done=all.filter(c=>state.progress[c.id]).length,pct=all.length?Math.round(done/all.length*100):0;el.progressText.textContent=`${done} / ${all.length} 已完成`;el.progressPct.textContent=pct+'%';el.progressFill.style.width=pct+'%'}
  function toggleProgress(id){state.progress[id]=!state.progress[id];save('study-progress',state.progress);render(el.search.value);syncMark();toast(state.progress[id]?'已标记完成':'已取消完成标记')}
  function syncMark(){if(!state.active){el.mark.disabled=true;return}el.mark.disabled=false;el.mark.textContent=state.progress[state.active.id]?'✓ 已完成':'标记完成'}
  function openCourse(c,s,push=true){state.active=c;state.activeSection=s;localStorage.setItem('gulu-last-course',c.id);el.wrap.classList.add('has-course');el.section.textContent=s.title;el.course.textContent=c.title;el.viewer.src=c.path;el.open.disabled=false;el.mark.disabled=false;el.notesTitle.textContent=c.title;loadNotes();syncMark();render(el.search.value);if(push)history.replaceState(null,'','#course='+encodeURIComponent(c.id));if(innerWidth<760)el.app.classList.remove('mobile-open')}
  function syncCourseFromFrame(path){const normalized=decodeURIComponent(String(path||'').replace(/^\.\//,'').split(/[?#]/)[0]);const c=allCourses().find(x=>x.path===normalized);if(!c||state.active?.id===c.id)return;state.active=c;state.activeSection=c.section;localStorage.setItem('gulu-last-course',c.id);el.section.textContent=c.section.title;el.course.textContent=c.title;el.open.disabled=false;el.mark.disabled=false;el.notesTitle.textContent=c.title;loadNotes();syncMark();render(el.search.value);history.replaceState(null,'','#course='+encodeURIComponent(c.id))}
  function currentNotesKey(){return state.active?'gulu-notes:'+state.active.path:''}
  function loadNotes(){state.notes=read(currentNotesKey(),[]);renderNotes()}
  function renderNotes(){el.noteCount.textContent=state.notes.length;el.notesList.innerHTML='';el.notesHint.style.display=state.notes.length?'none':'block';state.notes.forEach(n=>{const d=document.createElement('div');d.className='note';d.innerHTML=`<q>${esc(n.text)}</q><p>${esc(n.note)}</p><button title="删除">×</button>`;d.onclick=()=>scrollToNote(n.id);d.querySelector('button').onclick=e=>{e.stopPropagation();deleteNote(n.id)};el.notesList.appendChild(d)})}
  function deleteNote(id){state.notes=state.notes.filter(n=>n.id!==id);save(currentNotesKey(),state.notes);const doc=el.viewer.contentDocument,mark=doc?.querySelector(`[data-gulu-note="${CSS.escape(id)}"]`);if(mark)mark.replaceWith(...mark.childNodes);renderNotes();toast('笔记已删除')}
  function scrollToNote(id){const mark=el.viewer.contentDocument?.querySelector(`[data-gulu-note="${CSS.escape(id)}"]`);if(mark){mark.scrollIntoView({behavior:'smooth',block:'center'});mark.classList.add('flash');setTimeout(()=>mark.classList.remove('flash'),900)}}
  function xpath(node){if(node===node.ownerDocument.body)return'/body';const p=node.parentNode;if(!p)return'';const peers=[...p.childNodes].filter(x=>x.nodeType===node.nodeType&&x.nodeName===node.nodeName);return xpath(p)+'/'+(node.nodeType===3?'text()':node.nodeName.toLowerCase())+'['+(peers.indexOf(node)+1)+']'}
  function resolve(doc,path){try{return doc.evaluate(path,doc,null,XPathResult.FIRST_ORDERED_NODE_TYPE,null).singleNodeValue}catch{return null}}
  function wrap(doc,range,n){const m=doc.createElement('mark');m.className='gulu-highlight';m.dataset.guluNote=n.id;m.title=n.note;try{range.surroundContents(m)}catch{const f=range.extractContents();m.appendChild(f);range.insertNode(m)}return m}
  function injectNotes(){const doc=el.viewer.contentDocument;if(!doc||!state.active)return;let style=doc.getElementById('gulu-note-style');if(!style){style=doc.createElement('style');style.id='gulu-note-style';style.textContent='.gulu-highlight{background:rgba(255,206,103,.26)!important;border-bottom:2px solid rgba(255,206,103,.72);border-radius:2px;cursor:pointer}.gulu-highlight.flash{background:rgba(112,240,189,.55)!important}.selection-note{position:fixed;z-index:2147483647;border:0;border-radius:7px;background:#70f0bd;color:#04110b;padding:6px 11px;font:700 11px -apple-system,sans-serif;cursor:pointer;box-shadow:0 8px 25px rgba(0,0,0,.38)}';doc.head.appendChild(style)}
    state.notes.forEach(n=>{if(doc.querySelector(`[data-gulu-note="${CSS.escape(n.id)}"]`))return;const a=resolve(doc,n.startXPath),b=resolve(doc,n.endXPath);if(!a||!b)return;try{const r=doc.createRange();r.setStart(a,n.startOffset);r.setEnd(b,n.endOffset);wrap(doc,r,n)}catch{}});
    let button=null,lastRange=null;const clear=()=>{button?.remove();button=null};doc.addEventListener('mousedown',e=>{if(!e.target.closest?.('.selection-note'))clear()});doc.addEventListener('mouseup',e=>{if(e.target.closest?.('.selection-note'))return;setTimeout(()=>{const sel=doc.getSelection();if(!sel||sel.isCollapsed||!sel.rangeCount)return;lastRange=sel.getRangeAt(0).cloneRange();const text=lastRange.toString().trim();if(!text)return;clear();const rect=lastRange.getBoundingClientRect();button=doc.createElement('button');button.className='selection-note';button.textContent='+ 添加笔记';button.style.left=Math.max(8,rect.left+rect.width/2-38)+'px';button.style.top=Math.max(8,rect.top-35)+'px';button.onclick=()=>{const note=prompt('给这段文字写一条笔记：');if(!note||!lastRange)return;const n={id:crypto.randomUUID?crypto.randomUUID():Date.now().toString(36),text,startXPath:xpath(lastRange.startContainer),startOffset:lastRange.startOffset,endXPath:xpath(lastRange.endContainer),endOffset:lastRange.endOffset,note,createdAt:new Date().toISOString()};wrap(doc,lastRange,n);state.notes.push(n);save(currentNotesKey(),state.notes);renderNotes();doc.getSelection().removeAllRanges();clear();toast('笔记已保存')};doc.body.appendChild(button)},20)})
  }
  async function init(){try{const res=await fetch('courses.json');if(!res.ok)throw Error(res.status);state.data=await res.json();render();const hash=new URLSearchParams(location.hash.slice(1)).get('course'),id=hash||state.last;if(id){const c=allCourses().find(x=>x.id===id);if(c)openCourse(c,c.section,false)}else{const moon=allCourses().find(x=>x.id==='mc0');if(moon)state.continueCourse=moon}el.progressText.title='进度保存在当前浏览器 localStorage'}catch(e){el.list.innerHTML='<p style="padding:22px;color:var(--red)">课程目录加载失败。请通过 HTTP/iWiki 打开，而不是直接双击 file:// 页面。</p>';toast('courses.json 加载失败')}}
  window.addEventListener('message',e=>{if(e.source===el.viewer.contentWindow&&e.data?.type==='gulu:course-loaded')syncCourseFromFrame(e.data.path)});
  el.search.oninput=()=>render(el.search.value);el.viewer.onload=injectNotes;el.mark.onclick=()=>state.active&&toggleProgress(state.active.id);el.open.onclick=()=>state.active&&open(state.active.path,'_blank');$('#collapseSidebar').onclick=()=>{el.app.classList.add('folded');el.app.classList.remove('mobile-open')};$('#expandSidebar').onclick=()=>innerWidth<760?el.app.classList.add('mobile-open'):el.app.classList.remove('folded');$('#toggleNotes').onclick=()=>{state.notesOpen=!state.notesOpen;el.notes.classList.toggle('hidden',!state.notesOpen);$('#toggleNotes').classList.toggle('active',state.notesOpen);localStorage.setItem('gulu-notes-open',state.notesOpen?'1':'0')};$('#closeNotes').onclick=()=>$('#toggleNotes').click();$('#continueBtn').onclick=()=>{const c=allCourses().find(x=>x.id===state.last)||allCourses().find(x=>x.id==='mc0')||allCourses()[0];if(c)openCourse(c,c.section)};el.notes.classList.toggle('hidden',!state.notesOpen);$('#toggleNotes').classList.toggle('active',state.notesOpen);init();
})();
